### ISSUE TITLE
Day 1 Session 1: Introduction and the whole game

### ISSUE THREAD

**Issue by 3mmaRand** [rstudio-conf-2022/build-tidy-tools#2]
0900 - 1030
## Welcome and introductions ~15 mins
- Schedule for the workshop
- Guidelines, CoC, stickies

## Learning Objectives
At the end of this section you will be able to:
- find and explore their own package library/libraries
- describe the key components of a minimal package
- describe the different states a package can be in
- outline the development of a package using devtools
- create a simple version controlled package with a remote repo on GitHub
- use the package interactively with `load_all()`
- check package validity with `check()`

### Get to know your R installation
Version, R.home(), .Library .libPaths()
From: CRAN, GitHub, Bioconductor

### Developing a script vs developing a package
| Script | Pacakge
| ------ | -------- |
| one-off data analysis | defines reusable components
| defined by .R extension | defined by presence of DESCRIPTION file
| `library()` calls | Required packages specified in DESCRIPTION, made available in NAMESPACE file
| documentation in # comments | documentation in files and Roxygen comments
| `source()` | Install and restart

### Explore a package
use our demo pkg??

### Package states
- source
- bundled
- binary
- installed
- in-memory

## The Whole game
Making a minimal version controlled package linked to a remote repository on GitHub using the devtools approach.
`usethis::create_package`
  - new folder, restart, Build pane, .RProj 
  - infrastructure: DESCRIPTION, `R/`, NAMESPACE, .Rbuildignore .gitignore
 `usethis::use_r()` 
  - note the use_test() message
  - add a function 
 `devtools::load_all()`
 - explore in console
 - make a change, repeat
`devtools::check()`
  - errors, warnings, notes (perhaps our function should have an import which would then be listed in the warnings along with the lack of license)
`devtools::install()`
add roxygen skeleton and then `devtools::document()`,  (maybe leave until session 3)
`?function`
add a license (maybe leave until session 3)
edit DESCRIPTION
  - title, version, authors
Use git
 - git_sitrep()
 - use_git()
 - use_github()

**Comment by 3mmaRand** [comment]
Drafted 
Currently includes adding a license, documenting the function and altering the description. These might best be placed in a different session

**Comment by 3mmaRand** [comment]
adding license kept in. Moving doc to session two

**Comment by 3mmaRand** [comment]
Set up such as RStudio global options, .RProfile 
```
if (interactive()) {
  suppressMessages(require(devtools))
}
options(
  usethis.full_name = "Emma Rand",
  usethis.description = list(
    `Authors@R` = 'person("Emma", "Rand",
    email = "emma.rand@york.ac.uk",
    role = c("aut", "cre"),
    comment = c(ORCID = "0000-0001-6452-2420"))',
    License = "MIT + file LICENSE",
    Version = "0.0.0.9000"
  )
)
```
Should these be done first (added to the first session) or covered at the point of motivation e.g., when editing the description file manuallly.

**Comment by ijlyttle** [comment]
Just one opinion, but I'd be inclined to do this early - I think our students will appreciate us telling them of the "bad old days" without them having to go through it too much themselves.

One thing that I have come to appreciate: doing this causes side effects - very helpful side effects, but side effects nonetheless.

I am in the habit of doing virtually *all* of my non-package work in R using RMarkdown (and now Quarto). As you know, when we hit the "knit" (or "render") button, we are getting a completely clean environment which does not include these side-effects. This has a lot of benefits, which I did not appreciate initially.

**Comment by 3mmaRand** [comment]
Setup has been moved to first session.
